---
abstract: 'Allows a DBIx::Class user to define a Object::Enum column'
author:
  - 'Jason M. Mills <jmmills at cpan.org>'
build_requires:
  DBICx::TestDatabase: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-InflateColumn-Object-Enum
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class::Schema: 0
  Object::Enum: 0
  self: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
